# Create an Image
FROM openjdk:17.0.1
EXPOSE 5000
COPY /build/libs/test-module-second-0.0.1-SNAPSHOT.jar test-module-second-0.0.1-SNAPSHOT.jar
ENTRYPOINT exec java -jar test-module-second-0.0.1-SNAPSHOT.jar


